import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
// import Header from '@/components/Header';
// import Image from 'next/image';
// import pic from '@/public/img/pic.jpg';
// import { useEffect } from 'react';
// import firebase from '@/libs/firebase';


// import { useGlobalData } from '@/hooks/useGlobalContext';


export default function Home() {
	


	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				asdasd
			</main>
		</>
	);
}